name: Validate PR Metadata
on:
  pull_request_target:
    types:
      - labeled
      - unlabeled
      - opened
      - edited
      - reopened

jobs:
  validate_pr_metadata:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: CodeYourFuture/actions/validate-pr-metadata@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
